define({
	"login": {
		"user" : "اسم المستخدم",
		"pass": "كلمه السر",
		"title": "خدمات الذاتية الحديثة",
		"subtitle": "تطبيق ال",
		"lang" : "اختار اللغة"
	},
	"dashboard": {
		"title" : "لوحة القيادة",
		"notification": "إخطارات",
		"pendingapp": "في انتظار الموافقات",
		"quicklink": "روابط سريعة",
		"leaverequest": "طلب الإجازة",
		"employeeid": "معرف الموظف",
		"leavetab": "الإجازات",
		"instab": "التأمين الطبي",
		"dashboardtab": "الصفحة الرئيسية",
		"approve": "وافق",
		"reject": "رفض"
	},
	"insurance": {
		"medicalinsurance":"بدء التأمين الطبي للموظفين MOFA",
		"insuranceGrievance":"شكوى التأمين MOFA",
		"expenseReimbursment":"تسديد النفقات الطبية MOFA",
		"approveInsurance":"الموافقة على التأمين الطبي للموظفين MOFA",
		"approver": "الموافق",
		"select": "تحديد",
		"persontype": "نوع الشخص",
		"empno": "رقم الموظف",
		"name": "اسم",
		"arabicname": "الاسم العربي",
		"job": "وظيفة",
		"dob": "DOB",
		"idno": "ID No.",
		"phone": "هاتف",
		"city": "مدينة",
		"datecover": "غلاف التاريخ",
		"gender": "جنس",
		"status": "الحالة",
		"policyno": "رقم مركز الشرطه",
		"serviceprovider": "مقدم الخدمة",
		"claimref": "رقم المرجع الدعائي",
		"amount": "كمية",
		"remarks": "ملاحظات",
		"addressed": "تناولت",
		"approverremarks": "الموافقة على ملاحظات",
		"dateofclaim": "تاريخ المطالبة",
		"totalexp": "مجموع النفقات المتكبدة",
		"amountreim": "مبلغ السداد من قبل التأمين",
		"amountforreim": "المبلغ للسداد",
		"currency": "دقة",
		"medinsurance": "التأمين الطبي",
		"depref": "مرجع المرجع",
		"nationalid": "National ID",
		"document": "وثيقة",
		"expdate": "تاريخ الانتهاء",
		"approveddate": "تاريخ الموافقة",
		"action": "عمل",
		"reason": "السبب",
		"add": "إضافة"
	},
	"leave": {
		"leavesummary": "ملخص الأوراق",
		"btncreate": "إنشاء إجازة",
		"empname" : "اسم الموظف",
		"assignmentcategory": "فئة التعيين",
		"position": "موضع",
		"location": "موقعك",
		"empno": "رقم الموظف",
		"grade": "درجة",
		"dept": "قسم، أقسام",
		"startdate": "تاريخ البدء",
		"enddate": "تاريخ الانتهاء",
		"abstype": "نوع الغياب",
		"days": "أيام",
		"appstatus": "حالة القبول",
		"abstatus": "حالة الغياب",
		"leavetype": "نوع الإجازة السنوية",
		"decisiondate": "تاريخ القرار",
		"decisionfrom": "قرار من",
		"duration": "المدة الزمنية",
		"total": "مجموع الأيام",
		"replacedby": "وحل محله",
		"btnnext": "التالى",
		"applyleave": "تطبيق الإجازة",
		"confirmmessage": "تم إرسال طلب إجازتك للموافقة عليه",
		"approver": "الموافق",
		"lineno": "خط رقم",
		"category": "فئة غياب",
		"btnsubmit": "خضع",
		"btnback": "الى الخلف",
		"comment": "تعليق"
	}
});