define({
	root:
	{
		"login": {
			"user" : "Username",
			"pass": "Password",
			"title": "Modern Self Services",
			"subtitle": "Application",
			"lang" : "Select Language"
		},
		"dashboard": {
			"title" : "Dashboard",
			"notification": "NOTIFICATIONS",
			"pendingapp": "Pending Approvals",
			"quicklink": "Quick Links",
			"leaverequest": "Leave Request",
			"employeeid": "Employee ID",
			"leavetab": "Leaves",
			"instab": "Insurance",
			"dashboardtab": "Dashboard",
			"approve": "Approve",
			"reject": "Reject"
		},
		"insurance": {
			"medicalinsurance": "MOFA Initiate Employee Medical Insurance",
			"insuranceGrievance": "MOFA Insurance Grievance",
			"expenseReimbursment": "MOFA Medical Expense Reimbursement",
			"approveInsurance": "MOFA Approve Employee Medical Insurance",
			"approver": "Approvers",
			"select": "Select",
			"persontype": "Person Type",
			"empno": "Emp. No",
			"name": "Name",
			"arabicname": "Arabic Name",
			"job": "Job",
			"dob": "DOB",
			"idno": "ID No.",
			"phone": "Phone",
			"city": "City",
			"datecover": "Date Cover",
			"gender": "Gender",
			"status": "Status",
			"policyno": "Policy Number.",
			"serviceprovider": "Service Provider",
			"claimref": "Claim Reference Number",
			"amount": "Amount",
			"remarks": "Remarks",
			"addressed": "Addressed",
			"approverremarks": "Approver Remarks",
			"dateofclaim": "Date of Claim",
			"totalexp": "Total Expense Incurred",
			"amountreim": "Amount Reimbursement by Insurance",
			"amountforreim": "Amount For Reimbursement",
			"currency": "Currency",
			"medinsurance": "Medical Insurance",
			"depref": "Dep Reference",
			"nationalid": "National ID",
			"document": "Document",
			"expdate": "Expire Date",
			"approveddate": "Approved Date",
			"action": "Action",
			"reason": "Reason",
			"add": "Add"
		},
		"leave": {
			"leavesummary": "Leaves Summary",
			"btncreate": "Create Leave",
			"empname" : "Employee Name",
			"assignmentcategory": "Assignment Category",
			"position": "Position",
			"location": "Location",
			"empno": "Employee Number",
			"grade": "Grade",
			"dept": "Department",
			"startdate": "Start Date",
			"enddate": "End Date",
			"abstype": "Absense Type",
			"days": "Days",
			"appstatus": "Approval Status",
			"abstatus": "Absense Status",
			"leavetype": "Annual Leave Type",
			"decisiondate": "Decision Date",
			"decisionfrom": "Decision From",
			"duration": "Duration",
			"total": "Total Days",
			"replacedby": "Replaced By",
			"btnnext": "Next",
			"applyleave": "Apply Leave",
			"confirmmessage": "Your leave request has been sent for Approval",
			"approver": "Approver",
			"lineno": "Line No.",
			"category": "Absence Category",
			"btnsubmit": "Submit",
			"btnback": "Back",
			"comment": "Comment"
		}
		
	},
	"ar": true
});